### ISSUE TITLE
Error on loading .lvl files

### ISSUE THREAD

**Issue by superfrantv** [lcdr/utils#11]
I'm opening the luzviewer.pyw in Thonny (Python) and after loading a luz file this errors came out: Loading lvl nd_nimbus_station.lvl
Traceback (most recent call last):
  File "C:\Documents\Desktop\Tools\utils-master\utils\luzviewer.pyw", line 95, in load
    self._parse_lvl(ReadStream(lvl.read(), unlocked=True), scene)
  File "C:\Documents\Desktop\Tools\utils-master\utils\luzviewer.pyw", line 266, in _parse_lvl
    self._lvl_parse_chunk_type_2001(stream, scene)
  File "C:\Documents\Desktop\Tools\utils-master\utils\luzviewer.pyw", line 335, in _lvl_parse_chunk_type_2001
    lot_name += self.db.execute("select name from Objects where id == "+str(lot)).fetchone()[0]
sqlite3.OperationalError: no such table: Objects

**Comment by lcdr** [comment]
Closed as per communication, issue is not with luzviewer.
